import type { DynamoDbModelConfig, GraphqlScalar, KeyDef, ModelAttribute } from './types.js';

export interface GenerateSchemaOptions {
  /** Prepend a banner header. Default: the standard AUTOGENERATED notice. */
  header?: string;
  /**
   * Extra SDL to append verbatim (e.g. custom queries, mutations, unions).
   * Useful for mixing generated CRUD with hand-written fields.
   */
  extraSdl?: string;
}

interface Named {
  name: string;
  config: DynamoDbModelConfig;
}

/**
 * Emit a GraphQL schema covering the given DynamoDB models. For each model:
 *
 * - `type <Model>` with pk (and sk if present) + any declared `attributes`
 * - `type <Model>Connection` with `items` + `nextToken` for list responses
 * - `input Create<Model>Input` and `input Update<Model>Input`
 * - `Query.get<Model>` / `Query.list<Model>s`
 * - `Mutation.create<Model>` / `update<Model>` / `delete<Model>`
 *
 * Pair with `appSyncAdapter({ generateCrud: { models: 'all' } })` to wire
 * the generated operations to auto-CRUD resolvers.
 */
export function generateGraphQLSchema(
  models: Array<Named | DynamoDbModelConfig>,
  opts: GenerateSchemaOptions = {},
): string {
  const named = models.map(normalize);

  const header =
    opts.header ??
    '# AUTOGENERATED by `simple-cdk generate-schema`. Do not edit directly — your changes will be overwritten.';

  const types: string[] = [];
  const inputs: string[] = [];
  const queryFields: string[] = [];
  const mutationFields: string[] = [];

  for (const { name, config } of named) {
    const typeName = pascal(name);
    const fieldName = camel(name);
    const pk = config.pk;
    const sk = config.sk;

    const typeBody = buildTypeBody(pk, sk, config.attributes);
    types.push(`type ${typeName} {\n${typeBody}\n}`);
    types.push(
      `type ${typeName}Connection {\n  items: [${typeName}!]!\n  nextToken: String\n}`,
    );

    inputs.push(`input Create${typeName}Input {\n${buildCreateInputBody(pk, sk, config.attributes)}\n}`);
    inputs.push(`input Update${typeName}Input {\n${buildUpdateInputBody(pk, sk, config.attributes)}\n}`);

    queryFields.push(`  get${typeName}(${keyArgs(pk, sk)}): ${typeName}`);
    queryFields.push(`  list${typeName}s(limit: Int, nextToken: String): ${typeName}Connection`);

    mutationFields.push(`  create${typeName}(input: Create${typeName}Input!): ${typeName}`);
    mutationFields.push(`  update${typeName}(input: Update${typeName}Input!): ${typeName}`);
    mutationFields.push(`  delete${typeName}(${keyArgs(pk, sk)}): ${typeName}`);

    // Mark as intentionally used to satisfy strict compilers.
    void fieldName;
  }

  const parts: string[] = [header];
  if (types.length) parts.push(types.join('\n\n'));
  if (inputs.length) parts.push(inputs.join('\n\n'));
  parts.push(`type Query {\n${queryFields.join('\n') || '  _noop: String'}\n}`);
  if (mutationFields.length) parts.push(`type Mutation {\n${mutationFields.join('\n')}\n}`);
  if (opts.extraSdl) parts.push(opts.extraSdl.trimEnd());

  return parts.join('\n\n') + '\n';
}

function normalize(m: Named | DynamoDbModelConfig): Named {
  if ('config' in m) return m;
  if (!m.name) {
    throw new Error('generateGraphQLSchema: a model config was passed without `name` — supply { name, config } or set config.name.');
  }
  return { name: m.name, config: m };
}

function buildTypeBody(
  pk: KeyDef,
  sk: KeyDef | undefined,
  attrs: Record<string, ModelAttribute> | undefined,
): string {
  const lines: string[] = [];
  lines.push(`  ${pk.name}: ${keyScalar(pk)}!`);
  if (sk) lines.push(`  ${sk.name}: ${keyScalar(sk)}!`);
  for (const [name, attr] of Object.entries(attrs ?? {})) {
    lines.push(`  ${name}: ${renderType(attr)}`);
  }
  return lines.join('\n');
}

function buildCreateInputBody(
  pk: KeyDef,
  sk: KeyDef | undefined,
  attrs: Record<string, ModelAttribute> | undefined,
): string {
  const lines: string[] = [];
  lines.push(`  ${pk.name}: ${keyScalar(pk)}!`);
  if (sk) lines.push(`  ${sk.name}: ${keyScalar(sk)}!`);
  for (const [name, attr] of Object.entries(attrs ?? {})) {
    lines.push(`  ${name}: ${renderType(attr)}`);
  }
  return lines.join('\n');
}

function buildUpdateInputBody(
  pk: KeyDef,
  sk: KeyDef | undefined,
  attrs: Record<string, ModelAttribute> | undefined,
): string {
  const lines: string[] = [];
  lines.push(`  ${pk.name}: ${keyScalar(pk)}!`);
  if (sk) lines.push(`  ${sk.name}: ${keyScalar(sk)}!`);
  for (const [name, attr] of Object.entries(attrs ?? {})) {
    // Updates allow partial: strip required.
    lines.push(`  ${name}: ${renderType({ ...attr, required: false })}`);
  }
  return lines.join('\n');
}

function keyArgs(pk: KeyDef, sk: KeyDef | undefined): string {
  const args = [`${pk.name}: ${keyScalar(pk)}!`];
  if (sk) args.push(`${sk.name}: ${keyScalar(sk)}!`);
  return args.join(', ');
}

function keyScalar(k: KeyDef): GraphqlScalar {
  if (k.type === 'number') return 'Int';
  if (k.type === 'binary') return 'String';
  return k.name === 'id' ? 'ID' : 'String';
}

function renderType(attr: ModelAttribute): string {
  const inner = attr.list ? `[${attr.type}!]` : attr.type;
  return attr.required ? `${inner}!` : inner;
}

function pascal(s: string): string {
  return s
    .split(/[-_/\s]+/)
    .filter(Boolean)
    .map((p) => p[0]!.toUpperCase() + p.slice(1))
    .join('');
}

function camel(s: string): string {
  const p = pascal(s);
  return p[0]!.toLowerCase() + p.slice(1);
}
